schema_version = "1.0.0"
id = "gdp_1"
version = "0.1.0"
name = "Geometric Data Processing Assignment 1"
# >>>
maintainer = "Jackson Campolattaro, Nicolas Chaves-de-Plaza"
tagline = "An example implementation of Geometric Data Processing assignment 1."
# <<<
# ||| maintainer = "Add your names here!",
# ||| tagline = "A student implementation of Geometric Data Processing assignment 1.",
type = "add-on"
blender_version_min = "4.2.0"
license = [
    "SPDX:GPL-3.0-or-later",
]
wheels = [
    "../.wheels/numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "../.wheels/scipy-1.15.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "../.wheels/numpy-2.2.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "../.wheels/numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "../.wheels/scipy-1.15.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "../.wheels/numpy-2.2.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
]
